#! /bin/sh

SYSTEM=`uname -s`
if [ $SYSTEM = "Linux" ] ; then #"FreeBSD","Solaris"
	echo "Linux"
	NODE=node
elif [ $SYSTEM = "Darwin" ] ; then
	echo "Darwin"
	NODE=node_mac
else
	echo "What System?"
	NODE=node
fi

DAEMON="./$NODE start.js"
NAME=ddz
PIDFILE="game.pid"
OUTFILE="game.out"

case "$1" in
	start)
		if [ ! -f "$PIDFILE" ]; then
			netstat -an |grep *.$PORT
			echo "starting $NAME. "
			nohup $DAEMON > $OUTFILE &
			echo $! > $PIDFILE
			echo "started $!."
			tail -f $OUTFILE
		else
			echo "$NAME started."
		fi
				;;
	kill)
		if [ ! -f "$PIDFILE" ]; then
			echo "$NAME not start."
		else
			echo "stopping $NAME: "
			pid=`cat $PIDFILE`
			kill $pid
			rm $PIDFILE
			echo "stoped $pid."
		fi
			;;
	stop)
		killall -9 $NODE
		rm $PIDFILE
			;;
esac

exit 0;