{"status":200,"data":[{"requestId":"1","status":404,"action":"/user.checkThirdToken"},{"requestId":"2","status":200,"action":"/game.list","data":[{"gameId":1,"gameName":"欢乐斗地主","apiUrl":"http://ddz.h5.game.uc.cn:8022/","state":1,"gameUrl":"http://ddz.image.h5.game.uc.cn/games/ddz/index.html","thirdpartyType":0,"tag":5}]},{"requestId":"3","status":200,"action":"/notice.list","data":{"msgs":[{"content":"\u003clabel style\u003d\"color:#ffffff; font-size:26px;display:block;\"\u003e700人头血战激情互撸，不登王座人不退！狂撸\u003cspan style\u003d\"color:#00ff00;\"\u003e九游虫子前往论坛报名\u003c/span\u003e，即可参加\u003cspan style\u003d\"color:#00ff00;\"\u003e7月斗地主比赛战旗内测\u003c/span\u003e，话费、U宝、公仔抢到手软！\u003c/label\u003e      ","id":273005}],"interval":90}},{"requestId":"4","status":200,"action":"/superNotice.list","data":{"msgs":[],"interval":1800}},{"requestId":"5","status":200,"action":"/pop.list","data":{"msgs":[],"interval":1800}}]}
{"status":200,"data":[{"requestId":"8","status":200,"action":"/user.gameAuthorize","data":"a1b1428a-6e66-44fd-9638-96705eca2083-1611607"},{"requestId":"9","status":200,"action":"/box.gameNotice","data":{"message":""}}]}
{"status":200,"data":[{"requestId":"10","status":200,"action":"/user.heartbeat","data":{"exp":1213,"sTime":1372821452898,"isLvBonus":1}}],"cookies":[{"name":"rHTTime","path":"/","value":"1372821452894","maxAge":600},{"name":"hallToken","path":"/","value":"a01a5d72-45ff-4e75-9102-f6bb36313970","maxAge":7776000}]}
{"status":200,"data":[{"requestId":"11","status":200,"action":"/notice.list","data":{"msgs":[{"content":"\u003clabel style\u003d\"color:#ffffff; font-size:26px;display:block;\"\u003e700人头血战激情互撸，不登王座人不退！狂撸\u003cspan style\u003d\"color:#00ff00;\"\u003e九游虫子前往论坛报名\u003c/span\u003e，即可参加\u003cspan style\u003d\"color:#00ff00;\"\u003e7月斗地主比赛战旗内测\u003c/span\u003e，话费、U宝、公仔抢到手软！\u003c/label\u003e      ","id":273005}],"interval":90}}]}
{"status":200,"data":[{"requestId":"12","status":200,"action":"/user.heartbeat","data":{"exp":1222,"sTime":1372821512890,"isLvBonus":1}}]}
{"status":200,"data":[{"requestId":"13","status":200,"action":"/user.heartbeat","data":{"exp":1232,"sTime":1372821572890,"isLvBonus":1}}]}


{"status":200,"data":[{"requestId":"1","status":404,"action":"/user.checkThirdToken"},{"requestId":"2","status":200,"action":"/game.list","data":[{"gameId":1,"gameName":"欢乐斗地主","apiUrl":"http://ddz.h5.game.uc.cn:8022/","state":1,"gameUrl":"http://ddz.image.h5.game.uc.cn/games/ddz/index.html","thirdpartyType":0,"tag":5}]},{"requestId":"3","status":200,"action":"/notice.list","data":{"msgs":[],"interval":90}},{"requestId":"4","status":200,"action":"/superNotice.list","data":{"msgs":[],"interval":1800}},{"requestId":"5","status":200,"action":"/pop.list","data":{"msgs":[],"interval":1800}}]}
{"status":200,"data":[{"requestId":"7","status":200,"action":"/user.heartbeat","data":{"exp":1232,"sTime":1372821683871,"isLvBonus":1}}]}
{"status":200,"data":[{"requestId":"8","status":200,"action":"/user.heartbeat","data":{"exp":1242,"sTime":1372821743873,"isLvBonus":1}}]}
{"status":200,"data":[{"requestId":"9","status":200,"action":"/user.heartbeat","data":{"exp":1252,"sTime":1372821803872,"isLvBonus":1}}],"cookies":[{"name":"rHTTime","path":"/","value":"1372821803866","maxAge":600},{"name":"hallToken","path":"/","value":"f6a09ac2-c61d-4a9e-b92e-394328672b80","maxAge":7776000}]}

{"status":200,"data":[{"requestId":"11","status":200,"action":"/user.gameAuthorize","data":"bdaa7aca-1826-47f3-800f-1d70e158b8ef-1611607"},{"requestId":"12","status":200,"action":"/box.gameNotice","data":{"message":""}}]}


{"status":200,"data":[{"requestId":"19","status":200,"action":"/notice.list","data":{"msgs":[],"interval":90}}]}